### ISSUE TITLE
to be compatible with "peer" sni field

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/QvPlugin-Trojan#14]
Personally I think it totally nonsense to use `peer` for SNI. 
However, it may be necessary to support the field `peer`, since it's used by Shadowrocket.

Users are innocent. Just don't build another wall.

> Ref: https://github.com/Qv2ray/Qv2ray/issues/844

**Comment by ghost** [comment]
@DuckSoft Peer is not a standard. That's a shit name.
Ignored, anyone who wants it supported may open a PR.

**Comment by ghost** [comment]
@DuckSoft Users are innocent but the shit standard isn''t.

**Comment by DuckSoft** [comment]
https://github.com/v2board/v2board/pull/295
