### ISSUE TITLE
插件可否提供arm的版本

### ISSUE THREAD

**Issue by microjo** [Qv2ray/QvPlugin-Trojan#17]
rt.. 目前下载的linux-x64版本插件在arm64版qv2ray无法加载，是否可以提供arm64编译版本插件？

**Comment by darsvador** [comment]
@microjo 您可以自行编译

**Comment by DuckSoft** [comment]
备齐依赖，主要有 cmake boost qt5 

```bash
git clone --recursive https://github.com/Qv2ray/QvPlugin-Trojan
cd QvPlugin-Trojan
mkdir build
cmake ..
cmake --build .
cmake --install .
```

**Comment by microjo** [comment]
> 
> 
> 备齐依赖，主要有 cmake boost qt5
> 
> ```shell
> git clone --recursive https://github.com/Qv2ray/QvPlugin-Trojan
> cd QvPlugin-Trojan
> mkdir build
> cmake ..
> cmake --build .
> cmake --install .
> ```

在使用的机器上编译之后，将生成的libQvTrojanPlugin.so放到插件目录下面，重新打开qv2ray找不到插件。qv2ray是通过snap安装的软件包，版本2.6.3。

**Comment by DuckSoft** [comment]
@microjo 1. Snap 环境有隔离，记得放对位置，放错了可能会找不到。 @ymshenyu
2. 重新打开之前，确定 Qv2ray 完全退出了吗？

**Comment by microjo** [comment]
> 
> 
> @microjo 1. Snap 环境有隔离，记得放对位置，放错了可能会找不到。 @ymshenyu
> 2. 重新打开之前，确定 Qv2ray 完全退出了吗？

确定是退出 Qv2ray 之后，再打开。放置的目录是 Qv2ray 插件功能打开的本地插件目录。

**Comment by DuckSoft** [comment]
我错了，我之前没有意料到你是用 Snap 的就让你自己编译了……

来自本项目 Snapcraft、Debian 维护者 @ymshenyu：

> Snap 环境里的 Qt 版本很可能和你外面的 Qt 的版本不一样，因为符号表对不上，所以肯定无法加载。

你不妨贴一下你的实际操作系统的详细版本信息，我等下闲下来给你单独构建一份。

或者：其实之前我们是把 Trojan、SSR 插件打包进 Snapcraft 包里面的，也可以这样操作。
