### ISSUE TITLE
mac版本不能用

### ISSUE THREAD

**Issue by leo-je** [Qv2ray/QvPlugin-Trojan#22]
![image](https://user-images.githubusercontent.com/29834148/123926198-3ae48300-d9be-11eb-97ca-c6e11bf0a1a3.png)

**Comment by MarksonHon** [comment]
@leo-je 把你的主程序升级到2.7版本

**Comment by leo-je** [comment]
> @leo-je 把你的主程序升级到2.7版本

升级之后可以了。有个问题：节点如果套cdn后，安卓版的v2rayng可以正常使用，但是Qv不能使用
![image](https://user-images.githubusercontent.com/29834148/123931078-e1cb1e00-d9c2-11eb-851b-22156120c7dd.png)
是核心的问题吗
