### ISSUE TITLE
Trojan插件对前置代理的支持

### ISSUE THREAD

**Issue by gudong321** [Qv2ray/QvPlugin-Trojan#4]
对Qv2ray的发展关注很久了，有一些自己的想法和需求做个分享：

1. 现在的情况是不管是在大型科技企业、国企，还是科研院校，基本都是代理环境，正常科研技术工作的话，对科学上网，尤其是对Google搜索的需求非常大，然而，不知为什么，各种ss或者vmess协议经常被封，导致无法上网，目前只有采用网页伪装技术的Vmess+websocket+tls或者trojan协议可以正常科学上网。

2. 在单位的话，需要http代理才行，但也是最需要科学上网查找资料的时候，Vmess+websocket+tls的话，上游v2ray core貌似不支持前置代理，那么trojan支持前置代理的话，就能解决很多人的痛点了。

3. 一个软件如果既能解决大众痛点，又能做到方便易用，一定会很快推广起来。用proxychains-ng或者glider的话，很多人不太会用，而且比较麻烦，最好能集成到一个软件上，方便好用。

**Comment by DuckSoft** [comment]
你好，非常感谢你的宝贵建议。

事实上，Qv2ray 只是一个 V2Ray-Core / Trojan Core 的图形化前端，它的能力是不能逾越于其功能核心之上的。我非常理解你的想法，你可以把你的想法向这些核心上游报告。如果有幸上游添加了这些功能，我们届时非常乐意添加支持。

另外，我们一开始就没有打算让所有人使用 Qv2ray。Qv2ray 的目标用户，应该是那些愿意自己动手折腾、有一定电脑基础的用户。我们暂时不打算做成那种大包大揽的模样，不仅仅是因为我们菜、人少、没精力，更重要的是，我觉得，如果 Qv2ray 的目标用户群体真的对这个功能有强需求，这个功能一定有用户就帮我们实现了。
