### ISSUE TITLE
订阅功能有问题

### ISSUE THREAD

**Issue by JohnnyWoong** [Qv2ray/QvPlugin-Trojan#7]
提示有两个节点,但是服务器列表里不展示任何1个节点

**Comment by DuckSoft** [comment]
你好，请提供能让我们复现此问题所必须的信息。
非常抱歉，我们不会读心术。

**Comment by JohnnyWoong** [comment]
> 你好，请提供能让我们复现此问题所必须的信息。
> 非常抱歉，我们不会读心术。

我已录制视频
https://www.loom.com/share/a9556933eff540e09a69bc01da78bfa5

**Comment by DuckSoft** [comment]
你不妨复制你的订阅链接，在浏览器中打开，看看会是什么效果。
个人推测，上游订阅链接没有给你返回有效的节点。

**Comment by JohnnyWoong** [comment]
> 你不妨复制你的订阅链接，在浏览器中打开，看看会是什么效果。
> 个人推测，上游订阅链接没有给你返回有效的节点。

同样的订阅连接在 Trojan-Qt5 能正常订阅,复制到浏览器打开会下载一个txt文件

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/82723269-4d42b680-9d00-11ea-8fdd-a482f19026ea.png)
你好，我推测你因为没有安装 shadowsocksr 插件，导致上游返回的无效 shadowsocksr 节点被忽略掉了。

**Comment by JohnnyWoong** [comment]
安装后确实正常了...感谢
