### ISSUE TITLE
sync upstream

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/QvPlugin-Trojan#9]
we may have to sync with upstream https://github.com/trojan-gfw/trojan.

**Comment by ghost** [comment]
@DuckSoft The statistics patch needs to be updated.

**Comment by iambonboncat** [comment]
使用这个插件必须勾选Ignore certificate？

**Comment by DuckSoft** [comment]
> 使用这个插件必须勾选Ignore certificate？

正确填写 SNI 就不需要勾选跳过证书验证。
另外，跳过证书验证的风险请知悉：https://telegra.ph/%E6%9C%89%E5%85%B3-Trojan-%E5%85%B3%E9%97%AD%E8%AF%81%E4%B9%A6%E9%AA%8C%E8%AF%81%E7%9A%84%E5%AE%89%E5%85%A8%E8%AD%A6%E7%A4%BA-07-18

最后，你回错 issue 了，不要在 issue 里回复无关的东西。
